import { Sometype_Mono } from "next/font/google";
import "./globals.css";
import MainNav from "../../component/MainNav";
import PageTransition from "../../component/PageTransition";
import ReactA from "../../component/ReactA";
import Gradient from "../../component/Gradient";
import Header from "../../component/Header";
const sometypeMono =  Sometype_Mono({
  variable: "--font-sometypeMono",
  subsets: ["latin"],
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={` ${sometypeMono.variable} antialiased overflow-hidden relative` }
      >
        <Gradient/>
<ReactA/>
        <PageTransition >
        <div className="flex">
          <div className="hidden 2xl:flex w-[285px] h-screen bg-secondary">

         <MainNav/>
       </div>
       <div className="w-full max-w-[1130px] px-[15px] mx-auto ">
        <Header/>
           <div> {children}</div>
       </div>
        </div>
       </PageTransition>
    
      </body>
    </html>
  );
}
